using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace Otomasyon
{
    public partial class FRMURUNLER : Form
    {
        public FRMURUNLER()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        sqlbaglantisi bgl = new sqlbaglantisi();
        void listele()
        {
            DataTable dt = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter("Select * From TBL_URUNLER", bgl.baglanti());
            da.Fill(dt);
            gridControl1.DataSource = dt;

        }

        private void FRMURUNLER_Load(object sender, EventArgs e)
        {
            listele();
            temizle();

        }

        private void btnkaydet_Click(object sender, EventArgs e)
        {
            //Verileri kaydetme
            SqlCommand komut = new SqlCommand("insert into TBL_URUNLER (URUNAD,MARKA,MODEL,YIL,ADET,ALISFIYAT,SATISFIYAT,DETAY) values (@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8)", bgl.baglanti());
            komut.Parameters.AddWithValue("@p1", txtadi.Text);
            komut.Parameters.AddWithValue("@p2", txtmarka.Text);
            komut.Parameters.AddWithValue("@p3", txtmodel.Text);
            komut.Parameters.AddWithValue("@p4", txtyil.Text);
            komut.Parameters.AddWithValue("@p5", int.Parse((txtadet.Value).ToString()));
            komut.Parameters.AddWithValue("@p6", decimal.Parse(txtalisfiyat.Text));
            komut.Parameters.AddWithValue("@p7", decimal.Parse(txtsatisfiyat.Text));
            komut.Parameters.AddWithValue("@p8", txtdetay.Text);         
            komut.ExecuteNonQuery();
            bgl.baglanti().Close();
            MessageBox.Show("Urun basariyla kaydedildi!", "BILGI", MessageBoxButtons.OK, MessageBoxIcon.Information);
            listele();

        }

        private void btnsil_Click(object sender, EventArgs e)
        {
            SqlCommand komutsil = new SqlCommand("Delete From TBL_URUNLER where ID=@p1", bgl.baglanti());
            komutsil.Parameters.AddWithValue("@p1", txtid.Text);
            komutsil.ExecuteNonQuery();
            bgl.baglanti().Close();
            MessageBox.Show("Urun basariyla silindi", "BILGI", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            listele();
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            txtid.Text = dr["ID"].ToString();
            txtadi.Text = dr["URUNAD"].ToString();
            txtmarka.Text = dr["MARKA"].ToString();
            txtmodel.Text = dr["MODEL"].ToString();
            txtyil.Text = dr["YIL"].ToString();
            txtadet.Value = decimal.Parse(dr["ADET"].ToString());
            txtalisfiyat.Text = dr["ALISFIYAT"].ToString();
            txtsatisfiyat.Text = dr["SATISFIYAT"].ToString();
            txtdetay.Text = dr["DETAY"].ToString();
        }
        void temizle()
        {
            txtid.Text = "";
            txtadi.Text = "";
            txtmarka.Text = "";
            txtmodel.Text = ""; ;
            txtyil.Text = "";
            txtadet.Text = "";
            txtalisfiyat.Text = "";
            txtsatisfiyat.Text = "";
            txtdetay.Text = "";
            txtid.Text = "";
        }
      
        private void btntemizle_Click(object sender, EventArgs e)
        {
            temizle();
        }

        private void btnguncelle_Click(object sender, EventArgs e)
        {

            SqlCommand komut = new SqlCommand("update TBL_URUNLER set URUNAD=@P1,MARKA=@P2,MODEL=@P3,YIL=@P4,ADET=@P5,ALISFIYAT=@P6,SATISFIYAT=@P7,DETAY=@P8 where ID=@P9", bgl.baglanti());
            komut.Parameters.AddWithValue("@P1", txtadi.Text);
            komut.Parameters.AddWithValue("@P2", txtmarka.Text);
            komut.Parameters.AddWithValue("@P3", txtmodel.Text);
            komut.Parameters.AddWithValue("@P4", txtyil.Text);
        
            komut.Parameters.AddWithValue("@P5", int.Parse((txtadet.Value).ToString()));
            komut.Parameters.AddWithValue("@P6", decimal.Parse(txtalisfiyat.Text));
            komut.Parameters.AddWithValue("@P7", decimal.Parse(txtsatisfiyat.Text));
            komut.Parameters.AddWithValue("@P8", txtdetay.Text);
            komut.Parameters.Add("@P9", txtid.Text);
          
            komut.ExecuteNonQuery();
            bgl.baglanti().Close();
            MessageBox.Show("Urun basariyla guncellendi", "BILGI", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            listele();
        }


        private void btnkdv_Click(object sender, EventArgs e)
        {
            
           
        }
    }
}
